SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE `database`;
CREATE DATABASE `database`;
USE `database`;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `BRANCH` (
	BranchID int NOT NULL,
	Location varchar(255) DEFAULT NULL,
	ContactNo varchar(15) DEFAULT NULL,
	PRIMARY KEY(`BranchID`)
);

CREATE TABLE `EMPLOYEE` (
	EmployeeID int NOT NULL,
	Role varchar(255) DEFAULT NULL,
	Email varchar(255) DEFAULT NULL,
	Password varchar(255) DEFAULT NULL,
	FirstName varchar(255) DEFAULT NULL,
	LastName varchar(255) DEFAULT NULL,
	Salary decimal(10, 2) DEFAULT NULL,
	BranchID int DEFAULT NULL,
	PRIMARY KEY(`EmployeeID`),
	CONSTRAINT `fk_EMPLOYEE_BRANCH1` FOREIGN KEY (`BranchID`) REFERENCES `BRANCH` (`BranchID`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `CUSTOMER` (
	CustomerID int NOT NULL,
	Email varchar(255) DEFAULT NULL,
	Password varchar(255) DEFAULT NULL,
	FirstName varchar(255) DEFAULT NULL,
	LastName varchar(255) DEFAULT NULL,
	BranchID int DEFAULT NULL,
	PRIMARY KEY(`CustomerID`),
	CONSTRAINT `fk_CUSTOMER_BRANCH1` FOREIGN KEY (`BranchID`) REFERENCES `BRANCH` (`BranchID`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `SUPPLIER` (
	SupplierID int NOT NULL,
	Name varchar(255) DEFAULT NULL,
	ContactNo varchar(15) DEFAULT NULL,
	Address varchar(255) DEFAULT NULL,
	PRIMARY KEY(`SupplierID`)
);

CREATE TABLE `PRODUCT` (
	ProductID int NOT NULL,
	Name varchar(255) DEFAULT NULL,
	Category varchar(255) NOT NULL,
	Description varchar(255) DEFAULT NULL,
	Price decimal(10, 2) DEFAULT NULL,
	Stock int DEFAULT NULL,
	BranchID int DEFAULT NULL,
	SupplierID int DEFAULT NULL,
	PRIMARY KEY(`ProductID`),
	CONSTRAINT `fk_PRODUCT_BRANCH1` FOREIGN KEY (`BranchID`) REFERENCES `BRANCH` (`BranchID`) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT `fk_PRODUCT_SUPPLIER1` FOREIGN KEY (`SupplierID`) REFERENCES `SUPPLIER` (`SupplierID`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `ORDER` (
	OrderID int NOT NULL,
	Date date DEFAULT NULL,
	Cost decimal(10, 2) DEFAULT NULL,
	ProductID int DEFAULT NULL,
	CustomerID int DEFAULT NULL,
	PRIMARY KEY(`OrderID`),
	CONSTRAINT `fk_ORDER_PRODUCT1` FOREIGN KEY (`ProductID`) REFERENCES `PRODUCT` (`ProductID`) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT `fk_ORDER_CUSTOMER1` FOREIGN KEY (`CustomerID`) REFERENCES `CUSTOMER` (`CustomerID`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `BOOKMARK` (
	BookmarkID int NOT NULL,
	ProductId int DEFAULT NULL,
	CustomerId int DEFAULT NULL,
	TimeSaved timestamp DEFAULT NULL,
	PRIMARY KEY(`BookmarkID`),
	CONSTRAINT `fk_BOOKMARK_PRODUCT1` FOREIGN KEY (`ProductId`) REFERENCES `PRODUCT` (`ProductId`) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT `fk_BOOKMARK_CUSTOMER1` FOREIGN KEY (`CustomerID`) REFERENCES `CUSTOMER` (`CustomerID`) ON DELETE SET NULL ON UPDATE CASCADE
);

