SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `PRODUCT`;
DROP TABLE IF EXISTS `BRANCH`;
DROP TABLE IF EXISTS `SUPPLIER`;
DROP TABLE IF EXISTS `CUSTOMER`;
DROP TABLE IF EXISTS `ORDER`;
DROP TABLE IF EXISTS `EMPLOYEE`;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `BRANCH` (
	BranchID int NOT NULL, 
    Location varchar(255) DEFAULT NULL,
    ContactNo varchar(15) DEFAULT NULL,
	PRIMARY KEY (`BranchID`)
);

CREATE TABLE `EMPLOYEE` (
	EmployeeID int NOT NULL,
    EmployeeName varchar(255) DEFAULT NULL,
    Salary float(10, 2) DEFAULT NULL,
    BranchID int DEFAULT NULL,
    PRIMARY KEY (`EmployeeID`),
    CONSTRAINT `fk_Employee_Branch1` FOREIGN KEY (`BranchID`) REFERENCES `BRANCH` (`BranchID`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `SUPPLIER` (
	SupplierID int NOT NULL,
    `Name` varchar(255) DEFAULT NULL,
	ContactNo varchar(15) DEFAULT NULL,
    Address varchar(255) DEFAULT NULL,
    PRIMARY KEY (`SupplierID`)
);

CREATE TABLE `PRODUCT` ( 
	ProductID int NOT NULL,
    `Description` varchar(255) DEFAULT NULL,
    Price float(10, 2) DEFAULT NULL,
    Stock int DEFAULT NULL,
    Supplier varchar(255) DEFAULT NULL,
    BranchID int DEFAULT NULL,
    SupplierID int DEFAULT NULL,
    PRIMARY KEY(`ProductID`),
	CONSTRAINT `fk_Product_Branch1` FOREIGN KEY (`BranchID`) REFERENCES `BRANCH` (`BranchID`) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT `fk_Product_Supplier1` FOREIGN KEY (`SupplierID`) REFERENCES `SUPPLIER` (`SupplierID`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `CUSTOMER` (
	CustomerID int NOT NULL,
    `Name` varchar(255) DEFAULT NULL,
    BranchID int DEFAULT NULL,
    PRIMARY KEY(`CustomerID`),
    CONSTRAINT `fk_Customer_Branch1`FOREIGN KEY (`BranchID`) REFERENCES `BRANCH` (`BranchID`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `ORDER` (
	OrderID int NOT NULL,
    OrderDate date DEFAULT NULL,
    Cost float(10, 2) DEFAULT NULL,
    BranchID int DEFAULT NULL,
    PRIMARY KEY(`OrderID`),
    CONSTRAINT `fk_Order_Branch1` FOREIGN KEY (`BranchID`) REFERENCES `BRANCH` (`BRANCHID`) ON DELETE SET NULL ON UPDATE CASCADE
);